### ISSUE TITLE
Can you compile a windows binary?

### ISSUE THREAD

**Issue by SailorOnDaTea** [rafaelrinaldi/swf2html#2]
This is exactly what I am looking for to create html files for each swf in folder so I can share and watch them on HFS (HTTP File Server) via LAN. 

A batch file or command line like this would take care of it:

for %a in ("*.swf") do swf2html -f "%a" -t "%~na" -c 000 -w 80 -h 80 -ac true

can you make a binary for winXP and above?

**Comment by rafaelrinaldi** [comment]
@SailorOnDaTea Thanks for your interest on this little tool. As you can see I wrote it quite a few years ago when I used to work with Flash. That's no longer the case and I have very limited time on my hands right now. Unfortunately I won't spend time supporting it, I'm sorry.

If you want to give it a shot, I would be more than happy to add a WIndows binary to the project, though.

Also, I would recommend you using [Cygwin](https://www.cygwin.com) which makes Unix commands available on Windows.

Cheers.
